package tablas;
// Generated 28-may-2018 22:29:48 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name = "categorias", catalog = "nominas")
public class Categorias implements java.io.Serializable {

	private Integer idCategoria;
	private String nombreCategoria;
	private double salarioBaseCategoria;
	private double complementoCategoria;
	private Set trabajadorbbdds = new HashSet(0);

	public Categorias() {
	}

	public Categorias(String nombreCategoria, double salarioBaseCategoria, double complementoCategoria) {
		this.nombreCategoria = nombreCategoria;
		this.salarioBaseCategoria = salarioBaseCategoria;
		this.complementoCategoria = complementoCategoria;
	}

	public Categorias(String nombreCategoria, double salarioBaseCategoria, double complementoCategoria,
			Set trabajadorbbdds) {
		this.nombreCategoria = nombreCategoria;
		this.salarioBaseCategoria = salarioBaseCategoria;
		this.complementoCategoria = complementoCategoria;
		this.trabajadorbbdds = trabajadorbbdds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdCategoria", unique = true, nullable = false)
	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "NombreCategoria", nullable = false, length = 75)
	public String getNombreCategoria() {
		return this.nombreCategoria;
	}

	public void setNombreCategoria(String nombreCategoria) {
		this.nombreCategoria = nombreCategoria;
	}

	@Column(name = "SalarioBaseCategoria", nullable = false, precision = 22, scale = 0)
	public double getSalarioBaseCategoria() {
		return this.salarioBaseCategoria;
	}

	public void setSalarioBaseCategoria(double salarioBaseCategoria) {
		this.salarioBaseCategoria = salarioBaseCategoria;
	}

	@Column(name = "ComplementoCategoria", nullable = false, precision = 22, scale = 0)
	public double getComplementoCategoria() {
		return this.complementoCategoria;
	}

	public void setComplementoCategoria(double complementoCategoria) {
		this.complementoCategoria = complementoCategoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorias")
	public Set getTrabajadorbbdds() {
		return this.trabajadorbbdds;
	}

	public void setTrabajadorbbdds(Set trabajadorbbdds) {
		this.trabajadorbbdds = trabajadorbbdds;
	}

}
