package tablas;
// Generated 28-may-2018 22:29:48 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresas generated by hbm2java
 */
@Entity
@Table(name = "empresas", catalog = "nominas")
public class Empresas implements java.io.Serializable {

	private Integer idEmpresa;
	private String nombre;
	private String cif;
	private Set trabajadorbbdds = new HashSet(0);

	public Empresas() {
	}

	public Empresas(String nombre, String cif) {
		this.nombre = nombre;
		this.cif = cif;
	}

	public Empresas(String nombre, String cif, Set trabajadorbbdds) {
		this.nombre = nombre;
		this.cif = cif;
		this.trabajadorbbdds = trabajadorbbdds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdEmpresa", unique = true, nullable = false)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "Nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "CIF", nullable = false, length = 10)
	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresas")
	public Set getTrabajadorbbdds() {
		return this.trabajadorbbdds;
	}

	public void setTrabajadorbbdds(Set trabajadorbbdds) {
		this.trabajadorbbdds = trabajadorbbdds;
	}
	public int getId() {
		return idEmpresa;
	}

}
